version: '3'
networks:
 campus_virtual:

services:
  ud-observatorio-master:
     image: planesticud/ud-observatorio-master:latest
     container_name: ud-observatorio-master
     restart: on-failure
     env_file:
        - .env
     networks:
        - campus_virtual
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ud-observatorio-master.rule=Host(`observatorio.planestic.udistrital.edu.co`) && PathPrefix(`/api`)"
      - "traefik.http.routers.ud-observatorio-master.middlewares=ud-observatorio-master-stripprefix"
      - "traefik.http.middlewares.ud-observatorio-master-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.ud-observatorio-master.tls=true"
      - "traefik.http.routers.ud-observatorio-master.tls.certresolver=le"
      - "traefik.http.services.ud-observatorio-master.loadbalancer.server.port=80"           
networks:
  campus_virtual:
    external: true